apiVersion: batch/v1
kind: Job
metadata:
  name: job-a-1.34
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    version: "2"
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.33
        args:
        - /bin/sh
        - -c
        - sleep 5
      restartPolicy: Never
  backoffLimit: 4
