apiVersion: batch/v1
kind: Job
metadata:
  name: job-a
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.29.2
        args:
        - /bin/sh
        - -c
        - sleep 60
      restartPolicy: Never
  backoffLimit: 4
