apiVersion: batch/v1
kind: Job
metadata:
  name: job-b
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1.33
        args:
        - /bin/sh
        - -c
        - sleep 5
      restartPolicy: Never
  backoffLimit: 4
