apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: welcome-waves-and-hooks
resources:
- ../../base
- welcome-php-ns.yaml
#- welcome-php-postsync-pod.yaml
- welcome-php-presync-job.yaml
#- welcome-php-presync-pod.yaml
- job-a.yaml
- job-b.yaml
- my-configmap.yaml
- my-deployment.yaml
