apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  game.properties: |
    enemies=aliens
    lives=6
