apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-hooks
  namespace: openshift-gitops
spec:
  destination:
    namespace: welcome-hooks
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/welcome-php/overlays/hooks
    repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
